CC = i686-elf-gcc
AS = i686-elf-as
LD = i686-elf-ld

CFLAGS = -m32 -ffreestanding -O2 -Wall -Wextra -fno-pie -fno-stack-protector
ASFLAGS = --32
LDFLAGS = -m elf_i386 -T linker.ld -nostdlib


casino.bin: boot.o kernel.o
	$(LD) $(LDFLAGS) -o casino.bin boot.o kernel.o

boot.o: boot.s
	$(AS) $(ASFLAGS) boot.s -o boot.o

kernel.o: kernel.c
	$(CC) $(CFLAGS) -c kernel.c -o kernel.o

run: casino.bin
	qemu-system-i386 -kernel casino.bin

clean:
	rm -f *.o *.bin
